@PROTOCOL = http://
@HOSTNAME = localhost
@PORT = 8080
@HOST = {{HOSTNAME}}:{{PORT}}
@URL = {{PROTOCOL}}{{HOST}}
@API_END_POINT = {{URL}}/api/users

### 사용자 생성
POST {{API_END_POINT}}

{
    "name": "kyungeun",
    "arg": 99
}

### 전체 사용자 조회
GET {{API_END_POINT}}

### 사용자 조회
GET {{API_END_POINT}}/1

### 사용자 수정
PUT {{API_END_POINT}}/1

{
    "name": "이름 변경",
    "arg": 123
}

### 전체 사용자 삭제
DELETE  {{API_END_POINT}}

### 사용자 삭제
DELETE  {{API_END_POINT}}/1

### 사용자 로그인
POST {{API_END_POINT}}/login

### 사용자 카카오 로그인
GET {{API_END_POINT}}/login/kakao

### 사용자 로그아웃
POST {{API_END_POINT}}/logout

### 사용자 토큰 갱신
POST {{API_END_POINT}}/token/refresh