@URL = http://localhost:8080/api

### Server Health Check
GET {{URL}}/ping

### 사용자 생성
POST {{URL}}/users

{
    "name": "kyungeun",
    "arg": 99
}

### 전체 사용자 조회
GET {{URL}}/users

### 사용자 조회
GET {{URL}}/users/1

### 사용자 수정
PUT {{URL}}/users/1

{
    "name": "이름 변경",
    "arg": 123
}

### 전체 사용자 삭제
DELETE  {{URL}}/users

### 사용자 삭제
DELETE  {{URL}}/users/1