@URL = http://localhost:8080/api

###
GET {{URL}}/ping

###
POST {{URL}}/

{
    "name": "kyungeun",
    "arg": 99
}

###
GET {{URL}}/

###
PUT {{URL}}/2

{
    "name": "이름 변경",
    "arg": 123
}

###
DELETE  {{URL}}/2