version: "3.7"
services:
  mysql:
    build: .
    image: "mysql-modern-board"
    container_name: "dev-mysql-modern-board"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
    command:
      # 한글과 이모지 입력을 위하여 기본 문자셋 인코딩 변경
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
